### ISSUE TITLE
[UnleashedHUD] Runtime error with new mod loader and chip returns error

### ISSUE THREAD

**Issue by megasart** [PTKay/ModUpdates#7]
There is two current errors with the mod right now. The game can not run past the title loading screen with the mod on. It will have a runtime error and will asked to be closed.
The second error is that when the chip returns mod is loaded, no matter where it is in priority, the game will refuse to launch.

**Comment by PTKay** [comment]
1 - This error is caused by the SU Restorations mod, not the Unleashed HUD mod. Try disabling that mod. If the problem persists, reinstall the mod.
2 - I have nothing to do with the chip returns mod
